# Generated by Django 2.0.7 on 2020-03-26 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EmpInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=25)),
                ('email', models.EmailField(max_length=25)),
                ('password_first', models.CharField(max_length=25)),
                ('password_again', models.CharField(max_length=25)),
            ],
        ),
    ]
